[metadata]
name=UPD3305S
version=0.0.1
url=https://github.com/philpagel/UDP3305S.py
description=Remote control Uni-T UDP3305S and UPD3305S-E lab power supplies
long_description=file:README.md
[options]
package_dir =
   =src
packages = UDP3305S
python_requires=>=3.8,<4
install_requires=
   pyvisa
   pyvisa-py
   pyserial
